nombre = input(" ¿Como te llamas? ")
edad = input(" ¿Que edad tienes? ")
ciudad = input(" ¿De que ciudad eres? ")
hobby = input(" ¿Cual es tu Hobby? ")
print()
print()
print(f"Un momento, Generando tu tarjeta de presentacion...")
print()
print(f"Hola soy, {nombre}")
print(f"Y tengo {edad} años de edad,")
print(f"Vivo en {ciudad}")
print(f"Y mi Hobby es {hobby}")
print("Es un gusto conocerte!")